#!/bin/sh
read STATUS < /sys/class/drm/card0-HDMI-A-1/status

export XAUTHORITY=/home/jean/.Xauthority
export DISPLAY=:0

if [ "$STATUS" == "connected" ];
  then
    sleep 2;
    xrandr --output HDMI1 --primary --auto --right-of eDP1
    bspc monitor eDP1 -d 1
    bspc monitor HDMI1 -d 2 3 4 5 6 7 8 9 0
  else
    xrandr --output HDMI1 --off
    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
fi

feh --randomize --bg-fill /home/jean/wallpapers/1080p
/home/jean/.config/polybar/launch.sh &
