#! /bin/sh

sxhkd &

$HOME/.config/polybar/launch.sh

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

