templates:
  params:
    author-email: jean <dot> lopes <at> hotmail <dot> com <dot> br
    author-name: Jean Carlo Giambastiani Lopes
    category: web
    copyright: Copyright (c) 2020 Jean Carlo Giambastiani Lopes
    github-username: jean-lopes

